# SPDX-FileCopyrightText: 2021 Coop IT Easy SCRLfs
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Create and publish Docker image

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  schedule:
    - cron: "0 4 * * 1"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - odoo_version: "11.0"
            python_version: "3.6"
          - odoo_version: "12.0"
            python_version: "3.6"
          - odoo_version: "12.0"
            python_version: "3.7"
          - odoo_version: "12.0"
            python_version: "3.8"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch,prefix=${{ matrix.odoo_version }}-py${{ matrix.python_version }}-
            type=semver,pattern=${{ matrix.odoo_version }}.{{version}}-py${{ matrix.python_version }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            python_version=${{ matrix.python_version }}
            odoo_version=${{ matrix.odoo_version }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
